import {
  Check,
  Column,
  CreateDateColumn,
  Entity,
  Index,
  JoinColumn,
  ManyToOne,
  PrimaryColumn,
  Unique,
  UpdateDateColumn,
} from 'typeorm';
import type { Relation } from 'typeorm';
import { UserEntity } from '../../../users/entities/user.entity.js';
import { SessionRevokedReason } from '../enums/session-revoked-reason.enum.js';

/** Persistence model for `auth_sessions` (AUTH_DATABASE §3.3). One row per device/client. */
@Entity({ name: 'auth_sessions' })
@Unique('uq_auth_sessions_refresh_token_hash', ['refreshTokenHash'])
@Check(
  'ck_auth_sessions_revocation',
  `("revoked_at" IS NULL) = ("revoked_reason" IS NULL)`,
)
@Index('idx_auth_sessions_user_active', ['userId'], {
  where: `"revoked_at" IS NULL`,
})
@Index('idx_auth_sessions_expires_at', ['expiresAt'])
export class AuthSessionEntity {
  /** Generated by the app before signing, because it is embedded in tokens as `sid`. */
  @PrimaryColumn({
    name: 'id',
    type: 'uuid',
    primaryKeyConstraintName: 'pk_auth_sessions',
  })
  id: string;

  @Column({ name: 'user_id', type: 'uuid' })
  userId: string;

  @ManyToOne(() => UserEntity, { onDelete: 'CASCADE' })
  @JoinColumn({
    name: 'user_id',
    foreignKeyConstraintName: 'fk_auth_sessions_user',
  })
  user: Relation<UserEntity>;

  /** SHA-256 hex of the session's current refresh token. Never the raw token (SEC-TOKEN-02). */
  @Column({
    name: 'refresh_token_hash',
    type: 'char',
    length: 64,
    select: false,
  })
  refreshTokenHash: string;

  @Column({ name: 'expires_at', type: 'timestamptz' })
  expiresAt: Date;

  @Column({ name: 'revoked_at', type: 'timestamptz', nullable: true })
  revokedAt: Date | null;

  @Column({
    name: 'revoked_reason',
    type: 'enum',
    enum: SessionRevokedReason,
    enumName: 'session_revoked_reason',
    nullable: true,
  })
  revokedReason: SessionRevokedReason | null;

  @Column({ name: 'last_used_at', type: 'timestamptz', nullable: true })
  lastUsedAt: Date | null;

  @Column({ name: 'ip_address', type: 'varchar', length: 45, nullable: true })
  ipAddress: string | null;

  @Column({ name: 'user_agent', type: 'varchar', length: 512, nullable: true })
  userAgent: string | null;

  @CreateDateColumn({ name: 'created_at', type: 'timestamptz' })
  createdAt: Date;

  @UpdateDateColumn({ name: 'updated_at', type: 'timestamptz' })
  updatedAt: Date;
}
